### ISSUE TITLE
No such file or directory when trying to copy PDFs to Ipad

### ISSUE THREAD

**Issue by vanfanel** [programmin1/iosTransferGUI#4]
Hi there,

I'm using Ubuntu 16.04 to run iosTransferGUI. All dependencies were met and I built my own version from github.
iosTransferGUI gives this info about my device:

```
ActivationStateAcknowledged: true
BasebandStatus: NoTelephonyCapabilty
BluetoothAddress: 3c:15:c2:54:2e:1a
BoardId: 10
BrickState: false
BuildVersion: 13F69
CPUArchitecture: armv7f
ChipID: 35138
CompassCalibration: CwIGAAMA+P/l//r/WQD9/wAA/f/1/wEAWQBI2Q==
DeviceClass: iPad
DeviceColor: black
DeviceName: iPad de Mr Nutz
DieID: 2887971262057677972
EthernetAddress: 3c:15:c2:54:2e:1b
FirmwareVersion: iBoot-2817.50.3
HardwareModel: P105AP
HardwarePlatform: s5l8942x
HostAttached: true
MLBSerialNumber: C7L4274087RF570AR
ModelNumber: MF432
NonVolatileRAM: 
 auto-boot: dHJ1ZQ==
 backlight-level: MTY5Mw==
 boot-args: 
 oblit-begins: T2JsaXRUeXBlOiBPYmxpdGVyYXRlRGF0YVBhcnRpdGlvbi4gTm8gcmVhc29uIGdpdmVuLg==
 obliteration: aGFuZGxlX21lc3NhZ2U6IE9ibGl0ZXJhdGlvbiBDb21wbGV0ZQ==
PartitionType: 
PasswordProtected: true
ProductName: iPhone OS
ProductType: iPad2,5
ProductVersion: 9.3.2
ProductionSOC: true
ProtocolVersion: 2
ProximitySensorCalibration: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
RegionInfo: TY/A
SBLockdownEverRegisteredKey: false
SIMStatus: kCTSIMSupportSIMStatusReady
SerialNumber: F7NN2CHWFP84
SoftwareBehavior: AQAAAAAAAAAAAAAAAAAAAA==
SoftwareBundleVersion: 
SupportedDeviceFamilies[2]: 
 0: 1
 1: 2
TelephonyCapability: false
TimeIntervalSince1970: 1470405963.802384
TimeZone: Europe/Madrid
TimeZoneOffsetFromUTC: 7200.000000
TrustedHostAttached: true
UniqueChipID: 3850748797903
UniqueDeviceID: c0a7a8664ec1d489047996ac10549d71b1ebfc27
UseRaptorCerts: true
Uses24HourClock: false
WiFiAddress: 3c:15:c2:54:2e:19
WirelessBoardSerialNumber: 14185269770
```

As you can see, OS version is 9.3.2.
However, when I try to copy a PDF to the Ipad, I get:

> Transfer to: /run/user/1000/gvfs/afc:host=c0a7a8664ec1d489047996ac10549d71b1ebfc27,port=3
> Traceback (most recent call last):
>   File "./TransferGUI.py", line 175, in on_drag_data_received
>     book2pad.addbooks( iPadDir, url_splitted )
>   File "/home/manuel/src/iosTransferGUI/book2pad.py", line 96, in addbooks
>     tree, array = parse_plist(plist)
>   File "/home/manuel/src/iosTransferGUI/book2pad.py", line 48, in parse_plist
>     os.makedirs(os.path.dirname(plist))
>   File "/usr/lib/python2.7/os.py", line 150, in makedirs
>     makedirs(head, mode)
>   File "/usr/lib/python2.7/os.py", line 157, in makedirs
>     mkdir(name, mode)
> OSError: [Errno 2] No such file or directory: '/run/user/1000/gvfs/afc:host=c0a7a8664ec1d489047996ac10549d71b1ebfc27,port=3/Books'

Any ideas on what the problem could be here?
